config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#home'
  get 'about'=>'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #constants
  ROLES = {
    owner: 1,
    maintainer: 2,
    follower: 3
  }
  belongs_to :user
  belongs_to :post
  before_validate :befor_validatez
  after_validate :after_validatez
  validates :user_id, presence: true
  validates :user, uniqueness: { scope: :post,
        message: "Un usuario solo puede estar asociado una vez por projecto" }
  validates :rol, uniqueness: {scope: :post,
        message: "El proyecto solo puede tener un dueño" }, if: :is_owner?
  def befor_validatez
    binding.pry
    puts 'before'
  end
  def after_validatez
    binding.pry
    puts 'after'
  end
  def is_owner?
    self.rol == ROLES[:owner]
  end
end

app/models/concerns/post_owner_presence_validator.rb
class PostOwnerPresenceValidator < ActiveModel::Validator
  def validate(post)
    binding.pry
    owners_number = post.comments.select {|c| c.rol == 1}.count
    post.errors.add(:base, 'El proyecto debe de tener un dueño')
    if owners_number == 0
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :description, presence: true
  validates_associated :comments
  validates_with PostOwnerPresenceValidator
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  def squared_img
    if image.attached?
      image.variant(combine_options: { resize: '600x600^', gravity: 'center', extent: '600x600' })
    end
  end
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:phone])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
  end

  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  include Rails.application.routes.url_helpers

  def index
    @posts = Post.all
  end

  def show
    # @post.url = rails_blob_path(@post.image, disposition: "attachment", only_path: true)
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    binding.pry
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: '¡Post creado satisfactoriamente!'
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    binding.pry
    if @post.update(post_params)
      redirect_to @post, notice: '¡Post actualizado satisfactoriamente!'
    else
      binding.pry
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, alert: "¡No estás autorizada/o para editar este post!" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, comments_attributes: [
          :rol, :user_id, :_destroy, :id, :content
        ])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :phone, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :name, :phone, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Editing Post</h1>

<div class="text-center">
  <%# <%= image_tag @post.squared_img %> %>
</div>
<%= form_with(model: @comment, local: true, html:{method: :put}) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg ">
  <div class="container">
    <%#linkt "nombre a mostrar",ruta, clase-%>
    <%= link_to "Instagram", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "Quiénes somos", about_path, class: "nav-link" %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Mi cuenta", edit_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Cerrar sesión", destroy_user_session_path, class: "nav-link", method: :delete %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "Regístrate", new_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
    </li>
    <% end %>
  </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :cocoon %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> fade in">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>¿Quién soy?</h1>
<p>¡Un programador aprendiendo rails!</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<br/><%= link_to "Crear un post", new_post_path(@current_user), class: "btn btn-info btn-lg float-right" %>
<div class="jumbotron text-center">
 <h2>¡Bienvenidos a Instagram!</h2>
 <div class="main-wrapper">
   <div class="row">
     <% @posts.each do |post| %>
       <div class="col-xs-12 col-sm-6 col-md-4">
         <div class="image center-block">
           <%= link_to post.description, post_path(post) %>
         </div>
       </div>
     <% end %>
   </div>
 </div>
 <% else %>
   <h2>¡Bienvenidos a Instagram!</h2>
   <p>
     <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-default btn-lg" %>
     <%= link_to "Regístrate", new_user_registration_path, class: "btn btn-primary btn-lg" %>
   </p>
  <% end %>
</div>

app/views/posts/_comment_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :user_id %>
    <%= f.select :user_id, User.all.collect {|x| [x.name, x.id]}, :include_blank => false %>
  </div>
  <div class="field">
    <%= f.label :rol %>
    <%= f.select :rol, Comment::ROLES.map {|k,v| [k,v]}, :include_blank => false %>
    <%= link_to_remove_association "remove comment", f %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
    <%= link_to_remove_association "remove comment", f %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div id="comments">
    <%= f.simple_fields_for :comments do |comment| %>
      <%= render 'comment_fields', f: comment %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add comment', f, :comments %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<div class="text-center">
  <%# <%= image_tag @post.squared_img %> %>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<div class="text-center edit-links">
  <%= link_to "Borrar Post", post_path(@post), method: :delete, data: { confirm: "¿Estás segura que quieres eliminar este post?" } %>
  |
  <%= link_to "cancelar", posts_path %>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class="main-wrapper">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="image center-block">
            <%= link_to post.description,post_path(post) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="jumbotron text-center">
   <h1>¡Bienvenidos a Instagram!</h1>
     <p>
       <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Regístrate", new_user_registration_path, class: "btn btn-primary btn-lg" %>
     </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="image center-block">
      <%= image_tag @post.squared_img, class:'img-responsive' %>
    </div>
    <div class="post-bottom">
      <div class="description">
        <div class="user-name">
          <%= @post.user.name if @post.user %>
        </div>
        <%= @post.description %>
      </div>
      <% if @post.comments %>
        <% @post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-name">
              <%= comment.user.name %>
            </div>
            <div class="comment-content">
              <% if comment.user == current_user %>
                <%= link_to edit_post_comment_path(@post,comment), method: :get do %>
                  <%= comment.content %>
                <% end %>
              <% else %>
                <%= comment.content %>
              <% end %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(@post, comment), method: :delete, data: { confirm: "¿Estás segura?" } do %>
                <span class="glyphicon glyphicon-remove delete-comment">x</span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
    </div>
  </div>
</div>
<div class="text-center edit-links">
  <%= link_to "← Volver", posts_path %>
  |
  <% if @post.user == current_user %>
    <%= link_to "Editar Post", edit_post_path(@post) %>
  <% end %>
</div>